internal var systemStorage: [UInt64] = []

public func System<C0>(_ name: String, _ block: (Float, UnsafeMutablePointer<C0>) -> Void) -> Void where C0: Component {}
public func System<C0, C1>(_ name: String, _ block: (Float, UnsafeMutablePointer<C0>, UnsafeMutablePointer<C1>) -> Void) -> Void where C0: Component, C1: Component {}
public func System<C0, C1, C2>(_ name: String, _ block: (Float, UnsafeMutablePointer<C0>, UnsafeMutablePointer<C1>, UnsafeMutablePointer<C2>) -> Void) -> Void where C0: Component, C1: Component, C2: Component {}
public func System<C0, C1, C2, C3>(_ name: String, _ block: (Float, UnsafeMutablePointer<C0>, UnsafeMutablePointer<C1>, UnsafeMutablePointer<C2>, UnsafeMutablePointer<C3>) -> Void) -> Void where C0: Component, C1: Component, C2: Component, C3: Component {}
public func System<C0, C1, C2, C3, C4>(_ name: String, _ block: (Float, UnsafeMutablePointer<C0>, UnsafeMutablePointer<C1>, UnsafeMutablePointer<C2>, UnsafeMutablePointer<C3>, UnsafeMutablePointer<C4>) -> Void) -> Void where C0: Component, C1: Component, C2: Component, C3: Component, C4: Component {}
public func System<C0, C1, C2, C3, C4, C5>(_ name: String, _ block: (Float, UnsafeMutablePointer<C0>, UnsafeMutablePointer<C1>, UnsafeMutablePointer<C2>, UnsafeMutablePointer<C3>, UnsafeMutablePointer<C4>, UnsafeMutablePointer<C5>) -> Void) -> Void where C0: Component, C1: Component, C2: Component, C3: Component, C4: Component, C5: Component {}
public func System<C0, C1, C2, C3, C4, C5, C6>(_ name: String, _ block: (Float, UnsafeMutablePointer<C0>, UnsafeMutablePointer<C1>, UnsafeMutablePointer<C2>, UnsafeMutablePointer<C3>, UnsafeMutablePointer<C4>, UnsafeMutablePointer<C5>, UnsafeMutablePointer<C6>) -> Void) -> Void where C0: Component, C1: Component, C2: Component, C3: Component, C4: Component, C5: Component, C6: Component {}
public func System<C0, C1, C2, C3, C4, C5, C6, C7>(_ name: String, _ block: (Float, UnsafeMutablePointer<C0>, UnsafeMutablePointer<C1>, UnsafeMutablePointer<C2>, UnsafeMutablePointer<C3>, UnsafeMutablePointer<C4>, UnsafeMutablePointer<C5>, UnsafeMutablePointer<C6>, UnsafeMutablePointer<C7>) -> Void) -> Void where C0: Component, C1: Component, C2: Component, C3: Component, C4: Component, C5: Component, C6: Component, C7: Component {}
